### ISSUE TITLE
What is going wrong in firefox? Morphing gradient background is lagging on firefox

### ISSUE THREAD

**Issue by riojosdev** [baunov/gradients-bg#3]
I built my portfolio [riojos.in](https://riojos.in) using NEXT.js & created the background by following your tutorial. But I noticed the firefox rendering of the svg shader is slow. This happens only when the blur effect is applied.

Any idea on what is causing this?

**Comment by riojosdev** [comment]
I noticed your domain where your email is registered is not available. Is there an alternate address I could reach you

**Comment by baunov** [comment]
Resolved by https://github.com/baunov/gradients-bg/pull/4

**Comment by baunov** [comment]
Regarding the performance issue - hard to do anything. Reducing the gradients blocks size and blur size would help
